### ISSUE TITLE
Unblock Jekyll 4

### ISSUE THREAD

**Issue by damageboy** [clustergarage/jekyll-code-tabs#7]
Hi, I've hand-rolled a local version of this jekyll bundle with Jekyll 4.0 support, and everything seems to be in order...

Would you accept a PR allowing Jekyll 3..4 (Not incuding 5)?

**Comment by bfowle** [comment]
Hi, thanks for the PR! Merged it, let me know if you need a new version cut.

**Comment by damageboy** [comment]
Yeah, it would be nice to publish a 1.2 just so I don't have to build it myself for my blog :)
